import { VFC } from "react";
import Head from "next/head";
import { PopoverList } from "src/components/PopoverList";

const Home: VFC = () => {
  return (
    <>
      <Head>
        <title>onBoarding test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PopoverList />
    </>
  );
};

export default Home;
